### ISSUE TITLE
EA_AIP_DS_Full can not be validated

### ISSUE THREAD

**Issue by antoniolocandro** [aixm/donlon#21]
File in its current form does not pass validations for the XSD as it has invalid elements

Tried in Altova XML Spy
![image](https://user-images.githubusercontent.com/4627073/106658768-578da380-6563-11eb-9aad-911f3226fca3.png)

Tried in Notepad++
![image](https://user-images.githubusercontent.com/4627073/106658969-acc9b500-6563-11eb-89a9-bf7a52d67183.png)

**Comment by porosnie** [comment]
The file is valid when verifying it with Oxygen XML, configured to use both xerces and Saxon EE as validating parsers. Saxon also raises some warnings about the GML schema self inclusion, etc. This is beyond our control. 

XMLSpy and Notepad++ seem to be unable to deal with the schema declaration complexity. The errors that they raise are not related to the AIXM file itself, they are related to the schema declarations or the schema files. I do not know what XML parser these two are using. 

My recommendation is to use xerces for validation - https://xerces.apache.org/

**Comment by francois-germain** [comment]
Hi
I think the problem is not linked to the tools, but linked to the event schema referencing in the new version of the file.

The event schema references the http://www.aixm.aero/schema/5.1/event/Event_Features.xsd, instead of a 5.1.1 version, and I guess it induces the errors in XMLSpy (2017 for me), due to a double gml declaration coming from AIXM 5.1 and AIXM 5.1.1...

Eddy, and if I'm not wrong, I suggest the following:
- Correct the file so that it references a 5.1.1 event resource (not existing, see below)
- and so that it works, copy the http://www.aixm.aero/schema/5.1.1/event/version_5.1.1-f/*.xsd into http://www.aixm.aero/schema/5.1.1/event/


Normally, a tool like XMLSpy (2017+) should be able to validate AIXM 5 messages.

Antonio, in the meanwhile, when downloading the file, just remove the event part of the xsi:schemaLocation, and XMLSpy will validate.

**Comment by porosnie** [comment]
You are probably right! The Event schema declaration is not even necessary in the baseline Donlon sample. I think that it is simpler to just remove it.

**Comment by francois-germain** [comment]
Agreed, it would be better to have genuine AIXM 5 messages for the AIXM 5 samples.

**Comment by porosnie** [comment]
It's corrected. XMLSpy 2014 is happy now.
